openapi: 3.0.0
info:
  title: Orders API
  description: API for managing restaurant orders
  version: 1.0.0
servers:
  - url: http://localhost:3001/api
    description: Development server
paths:
  /orders:
    post:
      summary: Create a new order
      description: Place a new food order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customerId
                - orderType
                - items
              properties:
                customerId:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
                orderType:
                  type: string
                  enum: [delivery, pickup]
                items:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required:
                      - menuItemId
                      - quantity
                    properties:
                      menuItemId:
                        type: string
                        format: uuid
                      quantity:
                        type: integer
                        minimum: 1
                      specialInstructions:
                        type: string
                        maxLength: 200
                deliveryAddress:
                  $ref: '#/components/schemas/Address'
                specialInstructions:
                  type: string
                  maxLength: 500
                tipAmount:
                  type: number
                  format: decimal
                  minimum: 0
                paymentMethod:
                  type: string
                  enum: [credit-card, cash-on-delivery, digital-wallet]
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid order data
        '404':
          description: Menu item not found
        '500':
          description: Internal server error
  /orders/{id}:
    get:
      summary: Get order details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
        '500':
          description: Internal server error
  /orders/tracking/{trackingId}:
    get:
      summary: Track order status
      description: Get real-time order status by tracking ID
      parameters:
        - name: trackingId
          in: path
          required: true
          schema:
            type: string
            example: "ORD-20231225-001"
      responses:
        '200':
          description: Order tracking information
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                    format: uuid
                  trackingId:
                    type: string
                  status:
                    type: string
                    enum: [received, preparing, ready, out-for-delivery, ready-for-pickup, completed, cancelled]
                  estimatedTime:
                    type: string
                    format: date-time
                  statusHistory:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrderStatusHistory'
        '404':
          description: Order not found
        '500':
          description: Internal server error
  /orders/{id}/status:
    put:
      summary: Update order status
      description: Update the status of an order (admin/kitchen only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [received, preparing, ready, out-for-delivery, ready-for-pickup, completed, cancelled]
                notes:
                  type: string
                  maxLength: 500
      responses:
        '200':
          description: Order status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid status update
        '401':
          description: Unauthorized
        '404':
          description: Order not found
        '500':
          description: Internal server error
  /orders/customer/{customerId}:
    get:
      summary: Get customer's orders
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of customer's orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  total:
                    type: integer
        '404':
          description: Customer not found
        '500':
          description: Internal server error
components:
  schemas:
    Order:
      type: object
      required:
        - id
        - customerId
        - orderType
        - status
        - totalAmount
        - paymentStatus
        - trackingId
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        customerId:
          type: string
          format: uuid
        orderType:
          type: string
          enum: [delivery, pickup]
        status:
          type: string
          enum: [received, preparing, ready, out-for-delivery, ready-for-pickup, completed, cancelled]
        totalAmount:
          type: number
          format: decimal
        taxAmount:
          type: number
          format: decimal
        tipAmount:
          type: number
          format: decimal
        deliveryFee:
          type: number
          format: decimal
        paymentStatus:
          type: string
          enum: [pending, paid, failed, refunded]
        paymentMethod:
          type: string
          enum: [credit-card, cash-on-delivery, digital-wallet]
        deliveryAddress:
          $ref: '#/components/schemas/Address'
        pickupTime:
          type: string
          format: date-time
        deliveryTime:
          type: string
          format: date-time
        specialInstructions:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        trackingId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    OrderItem:
      type: object
      required:
        - id
        - menuItemId
        - quantity
        - unitPrice
        - subtotal
      properties:
        id:
          type: string
          format: uuid
        menuItemId:
          type: string
          format: uuid
        menuItemName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
          format: decimal
        subtotal:
          type: number
          format: decimal
        specialInstructions:
          type: string
    OrderStatusHistory:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [received, preparing, ready, out-for-delivery, ready-for-pickup, completed, cancelled]
        timestamp:
          type: string
          format: date-time
        notes:
          type: string
    Address:
      type: object
      required:
        - street
        - city
        - state
        - zipCode
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        country:
          type: string
          default: "US"
        apartment:
          type: string